### PR TITLE
Refactored Styling

### PR DESCRIPTION
**Pull request by lilpolymath**
#### Description
- Fixed the column thing and a couple of other issues.
- You didn't ask but for the dark mode thing, it would be easier to make use the colour as CSS variables I think it is easier that way.
- The toggle should be a button because of accessibility. Might do that if I am bored sha and you haven't done it.

That's all I think.

### CODE REVIEW

**Comment by Oluwaseunus** [comment]
Amazing PR @lilpolymath!

I have a couple of requests though since we're here. The design isn't exactly consistent among all screen sizes. I assume that's because you don't have the design assets, so I'll share them with you. You can see that the current implementation isn't exactly consistent with the design. I won't merge this PR yet, so you can complete it. Again, thanks for the amazing PR! :smile:

desktop-design-dark
mobile-design-dark

**Comment by lilpolymath** [comment]
Apart from the padding ish is there any other aspect?

**Comment by Oluwaseunus** [comment]
That and the number of cards per row

**Comment by lilpolymath** [comment]
Alright.

**Pull request merged**
